export interface Isolicitud {
    id?:string,
    periodo: string,
    solicitud:string,
    antiguo?:boolean,
    apellidos?:string,
    nombres?:string,
    celular?:string,
    certificado_trabajo?:string,
    codigo?:string,
    dni?:string,
    email?:string,
    idioma:string,
    nivel:string,
    numero_voucher?:string,
    facultad?:string,
    fecha_pago?:any | null,
    timestamp?:string,
    trabajador:boolean,
    voucher?:string,
    img_voucher?:string
    img_cert_estudio?:string,
    img_cert_trabajo?:string,
    img_dni?:string,
    estado?:string,
    pago:string,
    manual?:boolean,
    alumno_id?: string,
    creado?:any,
    modificado?:any
}